version: 2

project_name: gasmail

builds:
  - binary: gm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

brews:
  - name: gm
    repository:
      owner: nmelo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/nmelo/gasmail
    description: Persistent agent-to-agent messaging using beads
    license: MIT
    install: |
      bin.install "gm"
